In [4]:
import numpy as np

A = np.array([[0.24, 0.24, 0.17, 0.27, 0.12, 0.78, 0.86, 0.51, 0.08], [0.51, 0.91, 0.86, 0.32, 0.52, 0.61, 0.78, 0.67, 0.63], [0.92, 0.18, 0.34, 0.48, 0.41, 0.47, 0.47, 0.40, 0.23], [0.96, 0.17, 0.42, 0.74, 0.08, 0.77, 0.71, 0.76, 0.62], [0.96, 0.76, 0.92, 0.83, 0.04, 0.23, 0.59, 0.05, 0.10], [0.97, 0.51, 0.03, 0.50, 0.16, 0.47, 0.62, 0.87, 0.35], [0.21, 0.16, 0.29, 0.11, 0.53, 0.23, 0.62, 0.36, 0.10], [0.86, 0.36, 0.06, 0.41, 0.87, 0.69, 0.60, 0.24, 0.68]])
B = np.array([[0.17, 0.93, 0.49, 0.57, 0.43, 0.52, 0.96, 0.57, 0.19, 0.23, 0.13, 0.16], [0.72, 0.04, 0.49, 0.12, 0.40, 0.95, 0.67, 0.10, 0.73, 0.70, 0.30, 0.41], [0.68, 0.96, 0.02, 0.84, 0.25, 0.87, 0.51, 0.36, 0.24, 0.28, 0.51, 0.98], [0.41, 0.53, 0.41, 0.35, 0.38, 0.07, 0.57, 0.22, 0.62, 0.07, 0.42, 0.35], [0.78, 0.93, 0.89, 0.74, 0.82, 0.19, 0.65, 0.63, 0.06, 0.40, 0.35, 0.91], [0.97, 0.68, 0.57, 0.33, 0.58, 0.76, 0.79, 0.07, 0.50, 0.95, 0.51, 0.96], [0.54, 0.46, 0.73, 0.91, 0.58, 0.21, 0.99, 0.80, 0.69, 0.54, 0.69, 0.27], [0.59, 0.56, 0.70, 0.83, 0.35, 0.89, 0.40, 0.39, 0.77, 0.84, 0.99, 0.24], [0.21, 0.93, 0.39, 0.71, 0.73, 0.51, 0.21, 0.17, 0.20, 0.36, 0.96, 0.39]])

print(A @ B)

[[2.0722 1.9367 1.9167 2.0118 1.6308 1.8105 2.3982 1.3121 1.8283 2.0003
  1.9182 1.6417]
 [3.404  3.7242 2.9388 3.5336 2.8469 3.5441 3.7127 2.1244 2.6823 3.0158
  3.2117 3.0854]
 [2.0278 2.7986 2.0882 2.3811 1.9243 1.9859 2.7622 1.6327 1.6233 1.7495
  1.8729 1.8591]
 [2.6459 3.6218 2.6677 3.2098 2.5096 2.82   3.4689 1.9523 2.455  2.5177
  2.959  2.3218]
 [2.2997 2.8323 1.8729 2.4566 1.8611 2.4815 3.2059 1.6868 2.0556 1.6996
  1.8545 2.1248]
 [2.2598 2.7826 2.5392 2.6226 2.142  2.5206 3.0838 1.7532 2.2861 2.3256
  2.4252 1.6782]
 [1.5979 1.7675 1.5786 1.8231 1.3952 1.2983 1.8244 1.2677 1.1663 1.3529
  1.4524 1.4178]
 [2.5706 3.4102 2.8059 2.8268 2.7266 2.2462 3.2745 1.9236 1.8268 2.2692
  2.3834 2.4264]]


In [7]:
import numpy as np

A = np.array([[0.77, 0.31, 0.52, 0.00], [0.21, 0.13, 0.72, 0.74], [0.84, 0.07, 0.06, 0.91], [0.17, 0.71, 0.59, 0.10], [0.81, 0.32, 0.30, 0.84]])
B = np.array([[0.11, 0.15, 0.22, 0.40], [0.51, 0.81, 0.51, 0.65], [0.70, 0.90, 0.71, 0.17], [0.41, 0.06, 0.57, 0.58]])
C = np.array([[0.93, 0.51, 0.46, 0.42, 0.84], [0.31, 0.25, 0.24, 0.20, 0.15], [0.74, 0.37, 0.10, 0.05, 0.99], [0.10, 0.23, 0.65, 0.89, 0.18]])

X = (A @ B) @ C
print(X)

[[1.398398 0.913414 0.937737 0.988742 1.432257]
 [1.936756 1.217126 1.184151 1.23566  2.042355]
 [1.265961 0.850608 0.995639 1.143849 1.439475]
 [1.845596 1.19224  1.191642 1.234048 1.862322]
 [1.83916  1.215122 1.338296 1.483172 1.998297]]


In [2]:
import numpy as np

A = np.array([[0.40, 0.50], [1.30, 1.90]])
B = np.array([[0.50, 0.50], [0.30, 1.10]])
C = np.array([[0.50, 1.40], [1.50, 1.20]])


print(np.linalg.solve((A @ B @ A @ B @ B @ A @ B @ A), C) )

[[  1673920.27295214  20523727.504341  ]
 [ -1165728.00170557 -14292845.74539135]]


In [3]:
import numpy as np

A = np.array([[0.90, 0.30], [1.70, 1.10]])
B = np.array([[0.30, 1.90], [1.00, 1.80]])
C = np.array([[0.20, 0.30], [1.70, 0.10]])

# Y = np.linalg.solve(A,C).T
# Z = np.linalg.solve(B.T,Y).T #X 
# print(Z)

B_INV = np.linalg.inv(B)

print(np.linalg.solve((A),(C @ B_INV)))



[[ 1.25919118 -0.98192402]
 [-3.92463235  3.65655637]]
[[ 1.25919118 -0.98192402]
 [-3.92463235  3.65655637]]


In [11]:
  
A = np.array([[2.3, 2.4, 0.7, 0.7, 9.2, 0.5, 9.1],
 [3.6, 6.3, 8.2, 8.4, 0.3, 0.4, 2.9],
 [1.7, 10.0, 4.9, 0.8, 0.7, 1.5, 2.8],
 [1.9, 9.3, 1.2, 7.8, 8.6, 5.1, 9.9],
 [9.2, 7.3, 4.3, 4.5, 3.6, 4.3, 2.7],
 [2.2, 9.1, 9.1, 4.5, 7.1, 6.4, 4.5],
 [6.7, 2.7, 4.2, 8.2, 0.9, 9.6, 0.9]]
)

B = np.array([6.3, 4.8, 5.6, 1.6, 9.3, 0.5, 8.6])

print(np.linalg.solve(A,B))

[ 1.36788355 -0.49577165  0.55778932 -0.97158701 -1.88484495  0.6199826
  2.38065499]
